name: CI/CD Pipeline
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3


            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Install dependencies
              uses: borales/actions-yarn@v4
              with:
                  cmd: install # will run `yarn install` command

            - name: TypeScript Check
              run: yarn tsc

            - name: Run Tests
              run: yarn test

            - name: Build project
              run: yarn build
              env:
                  EMAIL_USER: ${{ secrets.EMAIL_USER }}
                  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
                  VITE_PUBLIC_GITHUB_TOKEN: ${{ secrets.VITE_PUBLIC_GITHUB_TOKEN }}

            - name: Upload production-ready build files
              uses: actions/upload-artifact@v3
              with:
                  name: production-files
                  path: ./dist
    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   name: Download artifact
                uses: actions/download-artifact@v3
                with:
                    name: production-files
                    path: ./dist

            -   name: Deploy to GitHub Pages
                uses: peaceiris/actions-gh-pages@v3
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./dist
